version: 2

models:
  - name: product_order_totals
    tests:
        - dbt_utils.equal_rowcount:
            compare_model: ref('all_order_products')
  
  - name: order_details

  - name: product_details

  - name: customer_orders

  - name: date_orders