version: 2

sources:
  - name: teddy_retailers
    description: These are the tables that our extraction software manages most likely through batch jobs. 
    tables:
      - name: source_customers
      - name: source_products
      - name: source_orders
      - name: source_order_products
  